2019-01-09 16:32:05,656 ERROR: Exception on / [GET] [in /home/michael/thundernugget/venv/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/michael/thundernugget/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/michael/thundernugget/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/michael/thundernugget/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/michael/thundernugget/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/michael/thundernugget/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/michael/thundernugget/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/michael/thundernugget/venv/lib/python3.6/site-packages/flask_login/utils.py", line 260, in decorated_view
    return current_app.login_manager.unauthorized()
  File "/home/michael/thundernugget/venv/lib/python3.6/site-packages/flask_login/login_manager.py", line 175, in unauthorized
    redirect_url = make_login_url(login_view, next_url=request.url)
  File "/home/michael/thundernugget/venv/lib/python3.6/site-packages/flask_login/utils.py", line 112, in login_url
    base = expand_login_view(login_view)
  File "/home/michael/thundernugget/venv/lib/python3.6/site-packages/flask_login/utils.py", line 89, in expand_login_view
    return url_for(login_view)
  File "/home/michael/thundernugget/venv/lib/python3.6/site-packages/flask/helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/michael/thundernugget/venv/lib/python3.6/site-packages/flask/app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/michael/thundernugget/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/michael/thundernugget/venv/lib/python3.6/site-packages/flask/helpers.py", line 345, in url_for
    force_external=external)
  File "/home/michael/thundernugget/venv/lib/python3.6/site-packages/werkzeug/routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'auth.login'. Did you mean 'main.user' instead?
2019-01-09 17:22:59,347 INFO: Microblog startup [in /home/michael/thundernugget/app/__init__.py:76]
2019-01-09 17:30:10,804 INFO: Microblog startup [in /home/michael/thundernugget/app/__init__.py:76]
2019-01-09 19:43:08,249 INFO: Microblog startup [in /home/michael/thundernugget/app/__init__.py:76]
2019-01-09 19:47:12,509 INFO: Microblog startup [in /home/michael/thundernugget/app/__init__.py:76]
2019-01-09 19:47:18,161 ERROR: Exception on /search [GET] [in /home/michael/thundernugget/venv/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/michael/thundernugget/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/michael/thundernugget/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/michael/thundernugget/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/michael/thundernugget/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/michael/thundernugget/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/michael/thundernugget/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/michael/thundernugget/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/michael/thundernugget/app/main/routes.py", line 144, in search
    current_app.config['POSTS_PER_PAGE'])
  File "/home/michael/thundernugget/app/models.py", line 16, in search
    ids, total = query_index(cls.__tablename__, expression, page, per_page)
  File "/home/michael/thundernugget/app/search.py", line 18, in query_index
    if not current_app.elasticsearch:
NameError: name 'current_app' is not defined
2019-01-09 19:47:23,029 ERROR: Exception on /search [GET] [in /home/michael/thundernugget/venv/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/michael/thundernugget/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/michael/thundernugget/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/michael/thundernugget/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/michael/thundernugget/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/michael/thundernugget/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/michael/thundernugget/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/michael/thundernugget/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/michael/thundernugget/app/main/routes.py", line 144, in search
    current_app.config['POSTS_PER_PAGE'])
  File "/home/michael/thundernugget/app/models.py", line 16, in search
    ids, total = query_index(cls.__tablename__, expression, page, per_page)
  File "/home/michael/thundernugget/app/search.py", line 18, in query_index
    if not current_app.elasticsearch:
NameError: name 'current_app' is not defined
2019-01-09 19:47:47,497 ERROR: Exception on /search [GET] [in /home/michael/thundernugget/venv/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/michael/thundernugget/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/michael/thundernugget/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/michael/thundernugget/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/michael/thundernugget/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/michael/thundernugget/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/michael/thundernugget/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/michael/thundernugget/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/michael/thundernugget/app/main/routes.py", line 144, in search
    current_app.config['POSTS_PER_PAGE'])
  File "/home/michael/thundernugget/app/models.py", line 16, in search
    ids, total = query_index(cls.__tablename__, expression, page, per_page)
  File "/home/michael/thundernugget/app/search.py", line 18, in query_index
    if not current_app.elasticsearch:
NameError: name 'current_app' is not defined
2019-01-09 19:50:16,005 INFO: Microblog startup [in /home/michael/thundernugget/app/__init__.py:76]
2019-01-09 19:51:47,910 INFO: Microblog startup [in /home/michael/thundernugget/app/__init__.py:76]
2019-01-09 19:52:48,835 INFO: Microblog startup [in /home/michael/thundernugget/app/__init__.py:76]
2019-01-09 19:53:25,020 INFO: Microblog startup [in /home/michael/thundernugget/app/__init__.py:76]
2019-01-09 22:56:06,576 INFO: Microblog startup [in /home/michael/thundernugget/app/__init__.py:77]
2019-01-09 23:18:31,186 INFO: Microblog startup [in /home/michael/thundernugget/app/__init__.py:77]
2019-01-17 22:53:37,474 INFO: Microblog startup [in /home/michael/thundernugget/app/__init__.py:77]
